#{{- $fullName := include "wordpress.fullname" . -}}
#{{- if not (and (contains ".breeze.io" (index .Values.DOMAIN 0)) (eq (len .Values.DOMAIN) 1))}}
#apiVersion: certmanager.k8s.io/v1alpha1
#kind: Certificate
#metadata:
#  name: {{ $fullName }}-cert
#  namespace: ingress-nginx
#spec:
#  secretName: "{{ $fullName }}-secret"
#  dnsNames:
#  {{- range .Values.DOMAIN }}
#  {{- if not (contains ".breeze.io" .)}}
#  - {{ . | quote }}
#  {{- end }}
#  {{- end }}
#  issuerRef:
#    name: letsencrypt-issuer
#{{- end}}
#
#
