apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-cert
  namespace: vashist-app
spec:
  secretName: "{{ $fullName }}-secret"
  dnsNames:
  - .Values.DOMAIN
  issuerRef:
    name: letsencrypt-issuer
{{- end}}


