apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: vashist-app
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  type: ClusterIP

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  namespace: vashist-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-storage
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: vashist-app
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - image: percona:5.7.26-centos
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQLROOTPASS }}
            - name: MYSQL_DATABASE
              value: {{ .Values.DBNAME }}
            - name: MYSQL_USER
              value: {{ .Values.DBUSER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.DBPASSWORD }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          lifecycle:
            postStart:
              exec:
                command: ['/bin/bash','-c', 'mysql -u {{ .Values.DBUSER }} -p{{ .Values.DBPASSWORD }} -h {{ mysql-svc }}-mysql -e "show databases" | grep -m 1 {{ .Values.DBNAME }}']
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
