apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.fullname" . }}-mysql
  namespace: ingress-nginx
  labels:
    app: {{ template "wordpress.fullname" . }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ template "wordpress.fullname" . }}
    tier: mysql
  type: ClusterIP

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wordpress.fullname" . }}-mysql-pv-claim
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "wordpress.fullname" . }}-mysql
  namespace: ingress-nginx
  labels:
    app: {{ template "wordpress.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "wordpress.fullname" . }}
      tier: mysql
  template:
    metadata:
      labels:
        app: {{ template "wordpress.fullname" . }}
        tier: mysql
    spec:
      containers:
        - image: percona:5.7.26-centos
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQLROOTPASS }}
            - name: MYSQL_DATABASE
              value: {{ .Values.DBNAME }}
            - name: MYSQL_USER
              value: {{ .Values.DBUSER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.DBPASSWORD }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ template "wordpress.fullname" . }}-mysql-pv-claim
