apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: vashist-app
  labels:
    app: server-svc
    label: server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: ssh
      port: 22
      targetPort: 22

  selector:
    app: server
    tier: server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-pv-claim
  namespace: vashist-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-storage
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: server
  namespace: vashist-app
  labels:
    app: server
    tier: server
spec:
  selector:
    matchLabels:
      app: server
      tier: server
  template:
    metadata:
      labels:
        app: server
        tier: server
    spec:
      containers:
        - image: server
          name: server
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.DBNAME }}
            - name: MYSQL_USER
              value: {{ .Values.DBUSER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.DBPASSWORD }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/root/mysite/setup_server.sh"]
          ports:
            - containerPort: 3000
              name: csg-api
          volumeMounts:
            - name: server-persistent-storage
              mountPath: /root/mysite
          readinessProbe:
            exec:
              command: ['/bin/bash','-c', 'node -v']
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
      #      imagePullSecrets:
      #        - name: gitlab-registry
      volumes:
        - name: server-persistent-storage
          persistentVolumeClaim:
            claimName: server-pv-claim
