apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.fullname" . }}
  namespace: ingress-nginx
  labels:
    app: {{ template "wordpress.fullname" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: ssh
      port: 22
      targetPort: 22

  selector:
    app: {{ template "wordpress.fullname" . }}
    tier: frontend
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wordpress.fullname" . }}-wp-pv-claim
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "wordpress.fullname" . }}
  namespace: ingress-nginx
  labels:
    app: {{ template "wordpress.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "wordpress.fullname" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ template "wordpress.fullname" . }}
        tier: frontend
    spec:
      containers:
        - image: 759046689382.dkr.ecr.us-east-1.amazonaws.com/sachin-repo
          name: breezewp
          env:
            - name: WORDPRESS_DB_HOST
              value: '{{ template "wordpress.fullname" . }}-mysql'
            - name: DBNAME
              value: {{ .Values.DBNAME }}
            - name: DBUSER
              value: {{ .Values.DBUSER }}
            - name: DBPASSWORD
              value: {{ .Values.DBPASSWORD }}
            - name: WPDOMAIN
              value: {{ .Values.WPDOMAIN }}
            - name: WPTITLE
              value: {{ .Values.WPTITLE }}
            - name: WPADMIN
              value: {{ .Values.WPADMIN }}
            - name: WPPASSWORD
              value: {{ .Values.WPPASSWORD }}
            - name: WPEMAIL
              value: {{ .Values.WPEMAIL }}
            - name: SSHROOTPASS
              value: {{ .Values.SSHROOTPASS }}
            - name: SSHUSERNAME
              value: {{ .Values.SSHUSERNAME }}
            - name: SSHUSERPASS
              value: {{ .Values.SSHUSERPASS }}
            - name: INSTANCEIP
              value: {{ .Values.INSTANCEIP }}
            - name: CONTAINERHTTPPORT
              value: {{ .Values.CONTAINERHTTPPORT }}
            - name: CONTAINERSSHPORT
              value: "{{ .Values.CONTAINERSSHPORT }}"
            - name: SITETYPE
              value: {{ .Values.SITETYPE }}
            - name: MYSQLROOTPASS
              value: {{ .Values.MYSQLROOTPASS }}
            - name: DOMAIN
              value: {{ .Values.WPDOMAIN }}
            - name: IS_WWW
              value: {{ .Values.IS_WWW }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/root/one_time_run.sh > /root/messages.log"]
          ports:
            - containerPort: 80
              name: wordpress
            - containerPort: 443
              name: wordpress-ssl
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /home/{{ template "wordpress.fullname" . }}/public_html
          readinessProbe:
            exec:
              command: ['/bin/bash','-c', 'mysql -u {{ .Values.DBUSER }} -p{{ .Values.DBPASSWORD }} -h {{ template "wordpress.fullname" . }}-mysql -e "show databases" | grep -m 1 {{ .Values.DBNAME }}']
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
#      imagePullSecrets:
#        - name: gitlab-registry
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ template "wordpress.fullname" . }}-wp-pv-claim
