import React from 'react';
import {makeStyles} from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import ButtonBase from '@material-ui/core/ButtonBase';

const useStyles = makeStyles(theme => ({
    image: {
        width: 200,
        height: 200,
    },
    img: {
        borderRadius:5,
        margin: 'auto',
        display: 'block',
        maxWidth: '100%',
        maxHeight: '100%',
    },
}));

export default function ComplexGrid() {
    const classes = useStyles();

    return (
        <Grid container spacing={6}>
            <Grid item>
                <ButtonBase className={classes.image}>
                    <img className={classes.img} alt="complex"
                         src="https://www.vrinsofts.com/wp-content/uploads/page//hire-dedicated-developer.png"/>
                </ButtonBase>
            </Grid>
            <Grid item xs={12} sm>
                <Typography color='textPrimary' variant='h4'>What i do ?</Typography>
                <Typography variant='h6' color='textSecondary'>
                    I Design, Code, Push, Build, Test, Deploy, Scale, Secure, Maintain ... Repeat!!
                </Typography>
                <Typography variant='body2'>
                    Starting from Designing an application, coding in ReactJs/Nodejs backed by mongoDb/mySql database,
                    Push and version maintaining through git,
                    Testing the build in CI/CD pipeline, Deploying it in docker environment(cloud),
                    Scaling it with Kubernetes System , Securing it with VPS and firewall, Maintaining through
                    analytics generated by Logs Monitoring System. And I <b> learn </b> and <b> REPEAT !! </b>
                </Typography>
            </Grid>

        </Grid>

    );
}
